-- MySQL Script generated by MySQL Workbench
-- Fri Oct 20 17:57:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_farmacia2017
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_farmacia2017
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_farmacia2017` DEFAULT CHARACTER SET utf8 ;
USE `bd_farmacia2017` ;

-- -----------------------------------------------------
-- Table `bd_farmacia2017`.`TB_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_farmacia2017`.`TB_CLIENTE` (
  `COD_CLI` INT NOT NULL AUTO_INCREMENT,
  `NOM_CLI` VARCHAR(30) NOT NULL,
  `APAT_CLI` VARCHAR(30) NOT NULL,
  `AMAT_CLI` VARCHAR(30) NOT NULL,
  `FEC_REG` DATE NULL,
  PRIMARY KEY (`COD_CLI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_farmacia2017`.`TB_CARGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_farmacia2017`.`TB_CARGO` (
  `COD_CARGO` INT NOT NULL AUTO_INCREMENT,
  `DESC_CARGO` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`COD_CARGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_farmacia2017`.`TB_EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_farmacia2017`.`TB_EMPLEADO` (
  `COD_EMP` INT NOT NULL AUTO_INCREMENT,
  `NOM_EMP` VARCHAR(30) NOT NULL,
  `APAT_EMP` VARCHAR(30) NOT NULL,
  `AMAT_EMP` VARCHAR(30) NOT NULL,
  `FEC_ING_EMP` DATE NOT NULL,
  `USER_EMP` VARCHAR(45) NOT NULL,
  `PASS_EMP` VARCHAR(45) NOT NULL,
  `COD_CARGO` INT NOT NULL,
  PRIMARY KEY (`COD_EMP`),
  INDEX `FK_EMP_CARGP_idx` (`COD_CARGO` ASC),
  CONSTRAINT `FK_EMP_CARGP`
    FOREIGN KEY (`COD_CARGO`)
    REFERENCES `bd_farmacia2017`.`TB_CARGO` (`COD_CARGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_farmacia2017`.`TB_LABORATORIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_farmacia2017`.`TB_LABORATORIO` (
  `COD_LAB` INT NOT NULL AUTO_INCREMENT,
  `DESC_LAB` VARCHAR(50) NULL,
  PRIMARY KEY (`COD_LAB`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_farmacia2017`.`TB_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_farmacia2017`.`TB_PRODUCTO` (
  `COD_PROD` INT NOT NULL AUTO_INCREMENT,
  `DESC_PRO` VARCHAR(70) NOT NULL,
  `PREC_PRO` DECIMAL(10,2) NOT NULL,
  `STK_ACT` INT NOT NULL,
  `STK_MIN` INT NOT NULL,
  `FEC_VENC` DATE NOT NULL,
  `COD_LAB` INT NOT NULL,
  PRIMARY KEY (`COD_PROD`),
  INDEX `FK_PRO_LAB_idx` (`COD_LAB` ASC),
  CONSTRAINT `FK_PRO_LAB`
    FOREIGN KEY (`COD_LAB`)
    REFERENCES `bd_farmacia2017`.`TB_LABORATORIO` (`COD_LAB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_farmacia2017`.`TB_VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_farmacia2017`.`TB_VENTA` (
  `NUM_VENTA` INT NOT NULL AUTO_INCREMENT,
  `FEC_VENTA` DATE NOT NULL,
  `EST_VENTA` SMALLINT NOT NULL,
  `COD_CLI` INT NOT NULL,
  `COD_EMP` INT NOT NULL,
  PRIMARY KEY (`NUM_VENTA`),
  INDEX `FK_VENTA_CLIENTE_idx` (`COD_CLI` ASC),
  INDEX `FK_VENTA_EMP_idx` (`COD_EMP` ASC),
  CONSTRAINT `FK_VENTA_CLIENTE`
    FOREIGN KEY (`COD_CLI`)
    REFERENCES `bd_farmacia2017`.`TB_CLIENTE` (`COD_CLI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VENTA_EMP`
    FOREIGN KEY (`COD_EMP`)
    REFERENCES `bd_farmacia2017`.`TB_EMPLEADO` (`COD_EMP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_farmacia2017`.`TB_DETALLE_VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_farmacia2017`.`TB_DETALLE_VENTA` (
  `COD_VENTA` INT NOT NULL,
  `COD_PRO` INT NOT NULL,
  `CANT_DVENTA` INT NOT NULL,
  `PREC_DVENTA` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`COD_VENTA`, `COD_PRO`),
  INDEX `FK_DETVENTA_PRO_idx` (`COD_PRO` ASC),
  CONSTRAINT `FK_DETVENTA_PRO`
    FOREIGN KEY (`COD_PRO`)
    REFERENCES `bd_farmacia2017`.`TB_PRODUCTO` (`COD_PROD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DETVENTA_VENTA`
    FOREIGN KEY (`COD_VENTA`)
    REFERENCES `bd_farmacia2017`.`TB_VENTA` (`NUM_VENTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


select * from tb_empleado;
select * from tb_empleado
where USER_EMP='' and PASS_EMP='';
select * from tb_cargo;

INSERT INTO bd_farmacia2017.tb_cargo
(DESC_CARGO)
VALUES('vendedor');


INSERT INTO bd_farmacia2017.tb_empleado
(NOM_EMP, APAT_EMP, AMAT_EMP, FEC_ING_EMP, USER_EMP, PASS_EMP, COD_CARGO)
VALUES('Emp1', 'apat1', 'mat1', '2017-10-24', 'abc', '123', 1);
